# first document
---
bitbake_target: curl-native
bitbake_ref: 1.34
oecore_ref: pyro
localconf: |
  LICENSE_FLAGS_WHITELIST = "commercial"
  SUPPORTED_RECIPES_CHECK = ""
dependencies:
  - url: git://git.openembedded.org/meta-openembedded
    ref: pyro
    layers:
      - meta-oe
---
# second document
---
bitbake_target: curl-native
configuration_name: latest
bitbake_ref: master
oecore_ref: master
localconf:
  LICENSE_FLAGS_WHITELIST = "commercial"
dependencies:
  - url: git://git.openembedded.org/meta-openembedded
    ref: master
    layers:
      - meta-oe
